### PR TITLE
made eval asynchronous

### PR DESCRIPTION
**Pull request by face-hh**
it works i checked in my bot, no more await is only valid in async function

### CODE REVIEW

**Review by Assassin-1234 — CHANGES_REQUESTED** [review]
please fix the lint errors

**Comment by face-hh** [comment]
wait im voting for nuggies rn :madge:

**Comment by face-hh** [comment]
> please fix the lint errors

what errors, it works fine

**Comment by Assassin-1234** [comment]
ESlint errors

**Comment by face-hh** [comment]
still didnt got it

**Comment by Assassin-1234** [comment]
nvm I'll fix it

**Pull request merged**
